// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

function assert$prime(condition, message) {
  if (condition) {
    return /* () */0;
  } else {
    return Pervasives.failwith(message);
  }
}

export {
  assert$prime ,
  
}
/* No side effect */
