// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Test$CircuitVisualiser from "./Test.bs.js";
import * as Greeting$CircuitVisualiser from "./Greeting.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Greeting$CircuitVisualiser.make, {
          name: "George"
        }), "greeting");

ReactDOMRe.renderToElementWithId(React.createElement(Test$CircuitVisualiser.make, {
          name: "George"
        }), "test");

export {
  
}
/*  Not a pure module */
