// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Test$CircuitVisualiser from "./Test.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Test$CircuitVisualiser.make, { }), "test");

export {
  
}
/*  Not a pure module */
