// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Greeting$CircuitVisualiser from "./Greeting.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Greeting$CircuitVisualiser.make, {
          name: "George"
        }), "greeting");

export {
  
}
/*  Not a pure module */
