// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function str(prim) {
  return prim;
}

function log(param) {
  console.log("Hey there!");
  return /* () */0;
}

function Test(Props) {
  return React.createElement("div", {
              className: "app"
            }, React.createElement("div", {
                  className: "title"
                }, "hello! ", React.createElement("button", {
                      onClick: (function (_evt) {
                          console.log("Hey there!");
                          return /* () */0;
                        })
                    }, "next circuit")));
}

var make = Test;

export {
  str ,
  log ,
  make ,
  
}
/* react Not a pure module */
